name: gh-action-pip-audit
run-name: gh-action-pip-audit

on:  
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10' 
      - uses: pypa/gh-action-pip-audit@v1.0.6
        with:
          inputs: requirements.txt
          no-deps: true
      - run: |
          pip install -r requirements.txt
          python -m black .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply black changes