name: gh-action-pip-audit
run-name: gh-action-pip-audit

on:  
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.10' 
      - uses: pypa/gh-action-pip-audit@v1.0.6
        with:
          inputs: requirements.txt
          no-deps: true